/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    pages: Page;
    posts: Post;
    media: Media;
    categories: Category;
    users: User;
    redirects: Redirect;
    forms: Form;
    'form-submissions': FormSubmission;
    search: Search;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    pages: PagesSelect<false> | PagesSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    redirects: RedirectsSelect<false> | RedirectsSelect<true>;
    forms: FormsSelect<false> | FormsSelect<true>;
    'form-submissions': FormSubmissionsSelect<false> | FormSubmissionsSelect<true>;
    search: SearchSelect<false> | SearchSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {
    header: Header;
    footer: Footer;
    settings: Setting;
  };
  globalsSelect: {
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    settings: SettingsSelect<false> | SettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: {
      schedulePublish: TaskSchedulePublish;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: string;
  title: string;
  hero: {
    type: 'none' | 'highImpact' | 'mediumImpact' | 'lowImpact' | 'slider' | 'lowGradient';
    gradientTitle?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    gradientSubtitle?: string | null;
    gradientBackground?: (string | null) | Media;
    gradientOverlayOpacity?: number | null;
    gradientHeight?: ('400px' | '520px' | '600px' | '100vh') | null;
    richText?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    links?:
      | {
          link: {
            type?: ('reference' | 'custom') | null;
            newTab?: boolean | null;
            reference?:
              | ({
                  relationTo: 'pages';
                  value: string | Page;
                } | null)
              | ({
                  relationTo: 'posts';
                  value: string | Post;
                } | null);
            url?: string | null;
            label: string;
            /**
             * Choose how the link should be rendered.
             */
            appearance?: ('default' | 'outline') | null;
          };
          id?: string | null;
        }[]
      | null;
    media?: (string | null) | Media;
    slider?: {
      mode?: ('static' | 'dynamic') | null;
      staticContent?: {
        /**
         * Use the toolbar to add formatted text and colors.
         */
        overlayText?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        cta?: {
          label?: string | null;
          url?: string | null;
        };
      };
      slides?:
        | {
            media: string | Media;
            id?: string | null;
          }[]
        | null;
      autoplay?: boolean | null;
      autoplaySpeed?: number | null;
      showArrows?: boolean | null;
      showDots?: boolean | null;
      height?: ('full' | 'large' | 'medium') | null;
      animationPreset?: ('slide' | 'fade' | 'cinematic') | null;
      overlayColor?: string | null;
    };
  };
  /**
   * Leave empty to use the default site background.
   */
  backgroundImage?: (string | null) | Media;
  /**
   * Applied as a transparent overlay over the background image.
   */
  overlayColor?: string | null;
  /**
   * 0 = fully transparent, 1 = solid colour.
   */
  overlayOpacity?: number | null;
  /**
   * How the inner blocks are constrained horizontally.
   */
  contentWidth?: ('contained' | 'full') | null;
  layout: (
    | CallToActionBlock
    | ContentBlock
    | MediaBlock
    | ArchiveBlock
    | FormBlock
    | {
        heading?: string | null;
        width?: ('contained' | 'full') | null;
        cardHeight?: number | null;
        cardColumns?: ('2' | '3' | '4') | null;
        overlayColor?: string | null;
        scrollAnimation?: ('none' | 'fadeUp' | 'fade' | 'slide') | null;
        items?:
          | {
              title: string;
              richDescription?: {
                root: {
                  type: string;
                  children: {
                    type: any;
                    version: number;
                    [k: string]: unknown;
                  }[];
                  direction: ('ltr' | 'rtl') | null;
                  format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                  indent: number;
                  version: number;
                };
                [k: string]: unknown;
              } | null;
              price?: number | null;
              image: string | Media;
              features?:
                | {
                    text?: string | null;
                    id?: string | null;
                  }[]
                | null;
              cta?: {
                label?: string | null;
                type?: ('internal' | 'external') | null;
                reference?: {
                  relationTo: 'pages';
                  value: string | Page;
                } | null;
                url?: string | null;
                newTab?: boolean | null;
              };
              id?: string | null;
            }[]
          | null;
        enableFooterCta?: boolean | null;
        footerCta?: {
          label: string;
          link: string;
          newTab?: boolean | null;
        };
        id?: string | null;
        blockName?: string | null;
        blockType: 'cardGrid';
      }
    | {
        backgroundImage: string | Media;
        overlay?: {
          type?: ('solid' | 'gradient') | null;
          /**
           * Use rgba() or hex with opacity
           */
          solidColor?: string | null;
          gradientDirection?: ('to bottom' | 'to top' | 'to right' | 'to left' | '135deg' | '45deg') | null;
          gradientStart?: string | null;
          gradientEnd?: string | null;
          /**
           * Where the first color ends (percentage)
           */
          gradientStopPosition?: number | null;
        };
        paddingTop?: number | null;
        paddingBottom?: number | null;
        /**
         * Set a custom height (CSS units like vh, px, %)
         */
        height?: string | null;
        /**
         * Color for the small welcome text above the title.
         */
        welcomeTextColor?: string | null;
        /**
         * Color for the main title text (fallback for unformatted text).
         */
        titleColor?: string | null;
        /**
         * Color for the description text.
         */
        descriptionColor?: string | null;
        title?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        welcomeText?: string | null;
        description?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        cta?: {
          label?: string | null;
          type?: ('internal' | 'external') | null;
          reference?: {
            relationTo: 'pages';
            value: string | Page;
          } | null;
          url?: string | null;
          newTab?: boolean | null;
        };
        scrollAnimation?: ('none' | 'fadeUp' | 'fade' | 'slideLeft' | 'slideRight') | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'parallaxHero';
      }
    | {
        title?: string | null;
        content: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        backgroundImage: string | Media;
        /**
         * Dark overlay on the left column to improve text readability
         */
        overlayOpacity?: number | null;
        textColor?: string | null;
        verticalPadding?: ('sm' | 'md' | 'lg' | 'xl') | null;
        enableButton?: boolean | null;
        button?: {
          label: string;
          link: string;
          newTab?: boolean | null;
          alignment?: ('left' | 'center' | 'right') | null;
        };
        id?: string | null;
        blockName?: string | null;
        blockType: 'splitContent';
      }
    | {
        mediaType?: ('youtube' | 'upload') | null;
        /**
         * Example: https://www.youtube.com/watch?v=pdzR0Tv8fcQ or just the ID
         */
        youtubeUrl?: string | null;
        uploadedVideo?: (string | null) | Media;
        /**
         * Optional – replaces video on mobile devices to improve performance.
         */
        mobilePlaceholder?: (string | null) | Media;
        autoplay?: boolean | null;
        loop?: boolean | null;
        muted?: boolean | null;
        controls?: boolean | null;
        overlayOpacity?: number | null;
        title?: string | null;
        subtitle?: string | null;
        description?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        enableButton?: boolean | null;
        button?: {
          label?: string | null;
          link?: string | null;
          newTab?: boolean | null;
        };
        verticalPadding?: ('sm' | 'md' | 'lg' | 'xl') | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'videoHero';
      }
    | {
        heading?: string | null;
        subheading?: string | null;
        items?:
          | {
              richContent?: {
                root: {
                  type: string;
                  children: {
                    type: any;
                    version: number;
                    [k: string]: unknown;
                  }[];
                  direction: ('ltr' | 'rtl') | null;
                  format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                  indent: number;
                  version: number;
                };
                [k: string]: unknown;
              } | null;
              title?: string | null;
              image: string | Media;
              link?: string | null;
              buttonLabel?: string | null;
              newTab?: boolean | null;
              id?: string | null;
            }[]
          | null;
        transitionSpeed?: ('slow' | 'medium' | 'fast') | null;
        columnHeight?: ('normal' | 'tall' | 'xtall') | null;
        desktopHeight?: ('default' | 'taller' | 'xtall' | 'custom') | null;
        customDesktopHeight?: number | null;
        buttonStyle?: ('gold' | 'white') | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'imageGrid';
      }
    | {
        heading?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        items?:
          | {
              icon?:
                | ('wifi' | 'pool' | 'beach' | 'umbrella' | 'sun' | 'restaurant' | 'spa' | 'gym' | 'parking' | 'pet')
                | null;
              titlePrefix?: string | null;
              title: string;
              description: {
                root: {
                  type: string;
                  children: {
                    type: any;
                    version: number;
                    [k: string]: unknown;
                  }[];
                  direction: ('ltr' | 'rtl') | null;
                  format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                  indent: number;
                  version: number;
                };
                [k: string]: unknown;
              };
              link: string;
              newTab?: boolean | null;
              id?: string | null;
            }[]
          | null;
        columns?: ('2' | '3' | '4') | null;
        backgroundColor?: string | null;
        verticalPadding?: ('sm' | 'md' | 'lg' | 'xl') | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'crossSectionCta';
      }
    | {
        heading?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        items?:
          | {
              image: string | Media;
              buttonLabel?: string | null;
              buttonLink: string;
              newTab?: boolean | null;
              /**
               * Use the toolbar to format title and description freely.
               */
              richContent: {
                root: {
                  type: string;
                  children: {
                    type: any;
                    version: number;
                    [k: string]: unknown;
                  }[];
                  direction: ('ltr' | 'rtl') | null;
                  format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                  indent: number;
                  version: number;
                };
                [k: string]: unknown;
              };
              id?: string | null;
            }[]
          | null;
        width?: ('contained' | 'full') | null;
        columns?: ('2' | '3' | '4') | null;
        cardHeight?: ('sm' | 'md' | 'tall' | 'xtall') | null;
        backgroundColor?: string | null;
        verticalPadding?: ('sm' | 'md' | 'lg' | 'xl') | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'cards';
      }
    | {
        heading?: string | null;
        slides?:
          | {
              image: string | Media;
              title?: string | null;
              description?: {
                root: {
                  type: string;
                  children: {
                    type: any;
                    version: number;
                    [k: string]: unknown;
                  }[];
                  direction: ('ltr' | 'rtl') | null;
                  format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                  indent: number;
                  version: number;
                };
                [k: string]: unknown;
              } | null;
              buttonLabel?: string | null;
              buttonLink?: string | null;
              newTab?: boolean | null;
              id?: string | null;
            }[]
          | null;
        showArrows?: boolean | null;
        autoplay?: boolean | null;
        autoplaySpeed?: number | null;
        showDots?: boolean | null;
        slidesPerView?: ('1' | '2' | '3' | '4') | null;
        gap?: number | null;
        /**
         * Used only if no gradient is provided.
         */
        backgroundColor?: string | null;
        /**
         * Applies to the solid background colour.
         */
        backgroundOpacity?: number | null;
        /**
         * Example: linear-gradient(135deg, #ffd28d, #040d10). Overrides solid colour.
         */
        backgroundGradient?: string | null;
        verticalPadding?: ('sm' | 'md' | 'lg' | 'xl') | null;
        width?: ('contained' | 'full') | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'slickerSlide';
      }
    | {
        heading?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        tabs?:
          | {
              tabName: string;
              items?:
                | {
                    title: string;
                    description?: string | null;
                    price?: string | null;
                    id?: string | null;
                  }[]
                | null;
              id?: string | null;
            }[]
          | null;
        columns?: ('1' | '2' | '3') | null;
        width?: ('contained' | 'full') | null;
        backgroundColor?: string | null;
        verticalPadding?: ('sm' | 'md' | 'lg' | 'xl') | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'menuTabs';
      }
    | {
        heading?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        subheading?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        categories?:
          | {
              tabLabel: string;
              sections?:
                | {
                    sectionHeading?: {
                      root: {
                        type: string;
                        children: {
                          type: any;
                          version: number;
                          [k: string]: unknown;
                        }[];
                        direction: ('ltr' | 'rtl') | null;
                        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                        indent: number;
                        version: number;
                      };
                      [k: string]: unknown;
                    } | null;
                    menuItems?:
                      | {
                          itemName: {
                            root: {
                              type: string;
                              children: {
                                type: any;
                                version: number;
                                [k: string]: unknown;
                              }[];
                              direction: ('ltr' | 'rtl') | null;
                              format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                              indent: number;
                              version: number;
                            };
                            [k: string]: unknown;
                          };
                          description?: {
                            root: {
                              type: string;
                              children: {
                                type: any;
                                version: number;
                                [k: string]: unknown;
                              }[];
                              direction: ('ltr' | 'rtl') | null;
                              format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                              indent: number;
                              version: number;
                            };
                            [k: string]: unknown;
                          } | null;
                          price: string;
                          id?: string | null;
                        }[]
                      | null;
                    id?: string | null;
                  }[]
                | null;
              id?: string | null;
            }[]
          | null;
        columnsPerRow?: ('2' | '3') | null;
        tableStyle?: ('default' | 'striped' | 'bordered') | null;
        /**
         * Leave empty or set to transparent for no background.
         */
        backgroundColor?: string | null;
        /**
         * Only applies if a background color is selected.
         */
        backgroundOpacity?: number | null;
        verticalPadding?: ('sm' | 'md' | 'lg' | 'xl') | null;
        width?: ('contained' | 'full') | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'menuTable';
      }
    | {
        images?:
          | {
              image: string | Media;
              alt?: string | null;
              link?: string | null;
              newTab?: boolean | null;
              id?: string | null;
            }[]
          | null;
        imageHeight?: number | null;
        gap?: number | null;
        desktopWidth?: ('45%' | '30%' | '22%' | '100%') | null;
        mobileWidth?: ('85%' | '100%') | null;
        borderRadius?: string | null;
        /**
         * CSS box-shadow value. Leave empty to disable.
         */
        boxShadow?: string | null;
        justifyContent?: ('space-around' | 'space-between' | 'center' | 'flex-start' | 'flex-end') | null;
        verticalPadding?: ('sm' | 'md' | 'lg' | 'xl') | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'imageRow';
      }
  )[];
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (string | null) | Media;
    description?: string | null;
    /**
     * Separate keywords with commas
     */
    keywords?: string | null;
  };
  publishedAt?: string | null;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt: string;
  caption?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  cloudinaryPublicId?: string | null;
  cloudinaryUrl?: string | null;
  cloudinaryResourceType?: string | null;
  cloudinaryFormat?: string | null;
  cloudinaryVersion?: number | null;
  /**
   * Direct URL to the original file without transformations
   */
  originalUrl?: string | null;
  /**
   * URL with applied transformations
   */
  transformedUrl?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  /**
   * File size in bytes
   */
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {};
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: string;
  title: string;
  heroImage?: (string | null) | Media;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  relatedPosts?: (string | Post)[] | null;
  categories?: (string | Category)[] | null;
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (string | null) | Media;
    description?: string | null;
  };
  publishedAt?: string | null;
  authors?: (string | User)[] | null;
  populatedAuthors?:
    | {
        id?: string | null;
        name?: string | null;
      }[]
    | null;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: string;
  title: string;
  slug?: string | null;
  /**
   * Optional image for this category
   */
  image?: (string | null) | Media;
  parent?: (string | null) | Category;
  breadcrumbs?:
    | {
        doc?: (string | null) | Category;
        url?: string | null;
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  name?: string | null;
  roles?: ('admin' | 'editor')[] | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CallToActionBlock".
 */
export interface CallToActionBlock {
  richText?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  links?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: string | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: string | Post;
              } | null);
          url?: string | null;
          label: string;
          /**
           * Choose how the link should be rendered.
           */
          appearance?: ('default' | 'outline') | null;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'cta';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentBlock".
 */
export interface ContentBlock {
  columns?:
    | {
        size?: ('oneThird' | 'half' | 'twoThirds' | 'full') | null;
        richText?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        enableLink?: boolean | null;
        /**
         * Align content inside the column
         */
        alignment?: ('left' | 'center' | 'right') | null;
        link?: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: string | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: string | Post;
              } | null);
          url?: string | null;
          label: string;
          /**
           * Choose how the link should be rendered.
           */
          appearance?: ('default' | 'outline') | null;
        };
        id?: string | null;
      }[]
    | null;
  /**
   * Maximum width of the content container. Leave empty for no max width.
   */
  containerMaxWidth?: number | null;
  /**
   * Leave empty or set to transparent for no background.
   */
  backgroundColor?: string | null;
  /**
   * Only applies if a background color is selected.
   */
  backgroundOpacity?: number | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'content';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaBlock".
 */
export interface MediaBlock {
  media: string | Media;
  /**
   * Leave empty for full width (within container)
   */
  width?: number | null;
  alignment?: ('left' | 'center' | 'right') | null;
  enableBackground?: boolean | null;
  backgroundColor?: string | null;
  backgroundPadding?: ('0' | 'p-4' | 'p-6' | 'p-8') | null;
  roundedCorners?: ('rounded-none' | 'rounded' | 'rounded-md' | 'rounded-lg' | 'rounded-xl' | 'rounded-full') | null;
  enableOverlay?: boolean | null;
  overlayOpacity?: number | null;
  caption?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  link?: string | null;
  newTab?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'mediaBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ArchiveBlock".
 */
export interface ArchiveBlock {
  introContent?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  populateBy?: ('collection' | 'selection') | null;
  relationTo?: 'posts' | null;
  categories?: (string | Category)[] | null;
  limit?: number | null;
  selectedDocs?:
    | {
        relationTo: 'posts';
        value: string | Post;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'archive';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FormBlock".
 */
export interface FormBlock {
  form: string | Form;
  enableIntro?: boolean | null;
  introContent?:
    | {
        [k: string]: unknown;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'formBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms".
 */
export interface Form {
  id: string;
  title: string;
  fields?:
    | (
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            defaultValue?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'checkbox';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'country';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'email';
          }
        | {
            message?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'message';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'number';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            placeholder?: string | null;
            options?:
              | {
                  label: string;
                  value: string;
                  id?: string | null;
                }[]
              | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'select';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'state';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'text';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'textarea';
          }
      )[]
    | null;
  submitButtonLabel?: string | null;
  /**
   * Choose whether to display an on-page message or redirect to a different page after they submit the form.
   */
  confirmationType?: ('message' | 'redirect') | null;
  confirmationMessage?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  redirect?: {
    url: string;
  };
  /**
   * Send custom emails when the form submits. Use comma separated lists to send the same email to multiple recipients. To reference a value from this form, wrap that field's name with double curly brackets, i.e. {{firstName}}. You can use a wildcard {{*}} to output all data and {{*:table}} to format it as an HTML table in the email.
   */
  emails?:
    | {
        emailTo?: string | null;
        cc?: string | null;
        bcc?: string | null;
        replyTo?: string | null;
        emailFrom?: string | null;
        subject: string;
        /**
         * Enter the message that should be sent in this email.
         */
        message?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects".
 */
export interface Redirect {
  id: string;
  /**
   * You will need to rebuild the website when changing this field.
   */
  from: string;
  to?: {
    type?: ('reference' | 'custom') | null;
    reference?:
      | ({
          relationTo: 'pages';
          value: string | Page;
        } | null)
      | ({
          relationTo: 'posts';
          value: string | Post;
        } | null);
    url?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions".
 */
export interface FormSubmission {
  id: string;
  form: string | Form;
  submissionData?:
    | {
        field: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This is a collection of automatically created search results. These results are used by the global site search and will be updated automatically as documents in the CMS are created or updated.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search".
 */
export interface Search {
  id: string;
  title?: string | null;
  priority?: number | null;
  doc: {
    relationTo: 'posts';
    value: string | Post;
  };
  slug?: string | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    image?: (string | null) | Media;
  };
  categories?:
    | {
        relationTo?: string | null;
        categoryID?: string | null;
        title?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: string;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'schedulePublish';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'schedulePublish') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'pages';
        value: string | Page;
      } | null)
    | ({
        relationTo: 'posts';
        value: string | Post;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'categories';
        value: string | Category;
      } | null)
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'redirects';
        value: string | Redirect;
      } | null)
    | ({
        relationTo: 'forms';
        value: string | Form;
      } | null)
    | ({
        relationTo: 'form-submissions';
        value: string | FormSubmission;
      } | null)
    | ({
        relationTo: 'search';
        value: string | Search;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  hero?:
    | T
    | {
        type?: T;
        gradientTitle?: T;
        gradientSubtitle?: T;
        gradientBackground?: T;
        gradientOverlayOpacity?: T;
        gradientHeight?: T;
        richText?: T;
        links?:
          | T
          | {
              link?:
                | T
                | {
                    type?: T;
                    newTab?: T;
                    reference?: T;
                    url?: T;
                    label?: T;
                    appearance?: T;
                  };
              id?: T;
            };
        media?: T;
        slider?:
          | T
          | {
              mode?: T;
              staticContent?:
                | T
                | {
                    overlayText?: T;
                    cta?:
                      | T
                      | {
                          label?: T;
                          url?: T;
                        };
                  };
              slides?:
                | T
                | {
                    media?: T;
                    id?: T;
                  };
              autoplay?: T;
              autoplaySpeed?: T;
              showArrows?: T;
              showDots?: T;
              height?: T;
              animationPreset?: T;
              overlayColor?: T;
            };
      };
  backgroundImage?: T;
  overlayColor?: T;
  overlayOpacity?: T;
  contentWidth?: T;
  layout?:
    | T
    | {
        cta?: T | CallToActionBlockSelect<T>;
        content?: T | ContentBlockSelect<T>;
        mediaBlock?: T | MediaBlockSelect<T>;
        archive?: T | ArchiveBlockSelect<T>;
        formBlock?: T | FormBlockSelect<T>;
        cardGrid?:
          | T
          | {
              heading?: T;
              width?: T;
              cardHeight?: T;
              cardColumns?: T;
              overlayColor?: T;
              scrollAnimation?: T;
              items?:
                | T
                | {
                    title?: T;
                    richDescription?: T;
                    price?: T;
                    image?: T;
                    features?:
                      | T
                      | {
                          text?: T;
                          id?: T;
                        };
                    cta?:
                      | T
                      | {
                          label?: T;
                          type?: T;
                          reference?: T;
                          url?: T;
                          newTab?: T;
                        };
                    id?: T;
                  };
              enableFooterCta?: T;
              footerCta?:
                | T
                | {
                    label?: T;
                    link?: T;
                    newTab?: T;
                  };
              id?: T;
              blockName?: T;
            };
        parallaxHero?:
          | T
          | {
              backgroundImage?: T;
              overlay?:
                | T
                | {
                    type?: T;
                    solidColor?: T;
                    gradientDirection?: T;
                    gradientStart?: T;
                    gradientEnd?: T;
                    gradientStopPosition?: T;
                  };
              paddingTop?: T;
              paddingBottom?: T;
              height?: T;
              welcomeTextColor?: T;
              titleColor?: T;
              descriptionColor?: T;
              title?: T;
              welcomeText?: T;
              description?: T;
              cta?:
                | T
                | {
                    label?: T;
                    type?: T;
                    reference?: T;
                    url?: T;
                    newTab?: T;
                  };
              scrollAnimation?: T;
              id?: T;
              blockName?: T;
            };
        splitContent?:
          | T
          | {
              title?: T;
              content?: T;
              backgroundImage?: T;
              overlayOpacity?: T;
              textColor?: T;
              verticalPadding?: T;
              enableButton?: T;
              button?:
                | T
                | {
                    label?: T;
                    link?: T;
                    newTab?: T;
                    alignment?: T;
                  };
              id?: T;
              blockName?: T;
            };
        videoHero?:
          | T
          | {
              mediaType?: T;
              youtubeUrl?: T;
              uploadedVideo?: T;
              mobilePlaceholder?: T;
              autoplay?: T;
              loop?: T;
              muted?: T;
              controls?: T;
              overlayOpacity?: T;
              title?: T;
              subtitle?: T;
              description?: T;
              enableButton?: T;
              button?:
                | T
                | {
                    label?: T;
                    link?: T;
                    newTab?: T;
                  };
              verticalPadding?: T;
              id?: T;
              blockName?: T;
            };
        imageGrid?:
          | T
          | {
              heading?: T;
              subheading?: T;
              items?:
                | T
                | {
                    richContent?: T;
                    title?: T;
                    image?: T;
                    link?: T;
                    buttonLabel?: T;
                    newTab?: T;
                    id?: T;
                  };
              transitionSpeed?: T;
              columnHeight?: T;
              desktopHeight?: T;
              customDesktopHeight?: T;
              buttonStyle?: T;
              id?: T;
              blockName?: T;
            };
        crossSectionCta?:
          | T
          | {
              heading?: T;
              items?:
                | T
                | {
                    icon?: T;
                    titlePrefix?: T;
                    title?: T;
                    description?: T;
                    link?: T;
                    newTab?: T;
                    id?: T;
                  };
              columns?: T;
              backgroundColor?: T;
              verticalPadding?: T;
              id?: T;
              blockName?: T;
            };
        cards?:
          | T
          | {
              heading?: T;
              items?:
                | T
                | {
                    image?: T;
                    buttonLabel?: T;
                    buttonLink?: T;
                    newTab?: T;
                    richContent?: T;
                    id?: T;
                  };
              width?: T;
              columns?: T;
              cardHeight?: T;
              backgroundColor?: T;
              verticalPadding?: T;
              id?: T;
              blockName?: T;
            };
        slickerSlide?:
          | T
          | {
              heading?: T;
              slides?:
                | T
                | {
                    image?: T;
                    title?: T;
                    description?: T;
                    buttonLabel?: T;
                    buttonLink?: T;
                    newTab?: T;
                    id?: T;
                  };
              showArrows?: T;
              autoplay?: T;
              autoplaySpeed?: T;
              showDots?: T;
              slidesPerView?: T;
              gap?: T;
              backgroundColor?: T;
              backgroundOpacity?: T;
              backgroundGradient?: T;
              verticalPadding?: T;
              width?: T;
              id?: T;
              blockName?: T;
            };
        menuTabs?:
          | T
          | {
              heading?: T;
              tabs?:
                | T
                | {
                    tabName?: T;
                    items?:
                      | T
                      | {
                          title?: T;
                          description?: T;
                          price?: T;
                          id?: T;
                        };
                    id?: T;
                  };
              columns?: T;
              width?: T;
              backgroundColor?: T;
              verticalPadding?: T;
              id?: T;
              blockName?: T;
            };
        menuTable?:
          | T
          | {
              heading?: T;
              subheading?: T;
              categories?:
                | T
                | {
                    tabLabel?: T;
                    sections?:
                      | T
                      | {
                          sectionHeading?: T;
                          menuItems?:
                            | T
                            | {
                                itemName?: T;
                                description?: T;
                                price?: T;
                                id?: T;
                              };
                          id?: T;
                        };
                    id?: T;
                  };
              columnsPerRow?: T;
              tableStyle?: T;
              backgroundColor?: T;
              backgroundOpacity?: T;
              verticalPadding?: T;
              width?: T;
              id?: T;
              blockName?: T;
            };
        imageRow?:
          | T
          | {
              images?:
                | T
                | {
                    image?: T;
                    alt?: T;
                    link?: T;
                    newTab?: T;
                    id?: T;
                  };
              imageHeight?: T;
              gap?: T;
              desktopWidth?: T;
              mobileWidth?: T;
              borderRadius?: T;
              boxShadow?: T;
              justifyContent?: T;
              verticalPadding?: T;
              id?: T;
              blockName?: T;
            };
      };
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
        keywords?: T;
      };
  publishedAt?: T;
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CallToActionBlock_select".
 */
export interface CallToActionBlockSelect<T extends boolean = true> {
  richText?: T;
  links?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
              appearance?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentBlock_select".
 */
export interface ContentBlockSelect<T extends boolean = true> {
  columns?:
    | T
    | {
        size?: T;
        richText?: T;
        enableLink?: T;
        alignment?: T;
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
              appearance?: T;
            };
        id?: T;
      };
  containerMaxWidth?: T;
  backgroundColor?: T;
  backgroundOpacity?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaBlock_select".
 */
export interface MediaBlockSelect<T extends boolean = true> {
  media?: T;
  width?: T;
  alignment?: T;
  enableBackground?: T;
  backgroundColor?: T;
  backgroundPadding?: T;
  roundedCorners?: T;
  enableOverlay?: T;
  overlayOpacity?: T;
  caption?: T;
  link?: T;
  newTab?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ArchiveBlock_select".
 */
export interface ArchiveBlockSelect<T extends boolean = true> {
  introContent?: T;
  populateBy?: T;
  relationTo?: T;
  categories?: T;
  limit?: T;
  selectedDocs?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FormBlock_select".
 */
export interface FormBlockSelect<T extends boolean = true> {
  form?: T;
  enableIntro?: T;
  introContent?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  heroImage?: T;
  content?: T;
  relatedPosts?: T;
  categories?: T;
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  publishedAt?: T;
  authors?: T;
  populatedAuthors?:
    | T
    | {
        id?: T;
        name?: T;
      };
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  cloudinaryPublicId?: T;
  cloudinaryUrl?: T;
  cloudinaryResourceType?: T;
  cloudinaryFormat?: T;
  cloudinaryVersion?: T;
  originalUrl?: T;
  transformedUrl?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?: T | {};
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  image?: T;
  parent?: T;
  breadcrumbs?:
    | T
    | {
        doc?: T;
        url?: T;
        label?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  roles?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects_select".
 */
export interface RedirectsSelect<T extends boolean = true> {
  from?: T;
  to?:
    | T
    | {
        type?: T;
        reference?: T;
        url?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms_select".
 */
export interface FormsSelect<T extends boolean = true> {
  title?: T;
  fields?:
    | T
    | {
        checkbox?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              defaultValue?: T;
              id?: T;
              blockName?: T;
            };
        country?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        email?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        message?:
          | T
          | {
              message?: T;
              id?: T;
              blockName?: T;
            };
        number?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        select?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              placeholder?: T;
              options?:
                | T
                | {
                    label?: T;
                    value?: T;
                    id?: T;
                  };
              required?: T;
              id?: T;
              blockName?: T;
            };
        state?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        text?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        textarea?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
      };
  submitButtonLabel?: T;
  confirmationType?: T;
  confirmationMessage?: T;
  redirect?:
    | T
    | {
        url?: T;
      };
  emails?:
    | T
    | {
        emailTo?: T;
        cc?: T;
        bcc?: T;
        replyTo?: T;
        emailFrom?: T;
        subject?: T;
        message?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions_select".
 */
export interface FormSubmissionsSelect<T extends boolean = true> {
  form?: T;
  submissionData?:
    | T
    | {
        field?: T;
        value?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search_select".
 */
export interface SearchSelect<T extends boolean = true> {
  title?: T;
  priority?: T;
  doc?: T;
  slug?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  categories?:
    | T
    | {
        relationTo?: T;
        categoryID?: T;
        title?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: string;
  navItems?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: string | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: string | Post;
              } | null);
          url?: string | null;
          label: string;
        };
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: string;
  layout?: ('simple' | 'advanced') | null;
  navItems?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: string | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: string | Post;
              } | null);
          url?: string | null;
          label: string;
        };
        id?: string | null;
      }[]
    | null;
  logo?: (string | null) | Media;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  socialBadges?:
    | {
        image: string | Media;
        link?: string | null;
        id?: string | null;
      }[]
    | null;
  reachUs?: {
    heading?: string | null;
    phone?: string | null;
    email?: string | null;
    hours?: string | null;
    partnerHotel?: {
      label?: string | null;
      logo?: (string | null) | Media;
      link?: string | null;
      newTab?: boolean | null;
    };
  };
  /**
   * Paste the full embed URL from Google Maps
   */
  mapEmbedUrl?: string | null;
  copyright?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings".
 */
export interface Setting {
  id: string;
  branding: {
    logo: string | Media;
    /**
     * Optional. Used on transparent/dark sections.
     */
    logoDark?: (string | null) | Media;
    logoWidthDesktop?: number | null;
    logoWidthMobile?: number | null;
    favicon?: (string | null) | Media;
    favicon16?: (string | null) | Media;
    appleTouchIcon?: (string | null) | Media;
    manifest?: (string | null) | Media;
    androidChrome192?: (string | null) | Media;
    androidChrome512?: (string | null) | Media;
  };
  defaultSeo?: {
    title?: string | null;
    description?: string | null;
    image?: (string | null) | Media;
  };
  /**
   * Separate keywords with commas
   */
  keywords?: string | null;
  /**
   * e.g., +1 (501) 226-2345 (Leave blank to hide)
   */
  phoneNumber?: string | null;
  navItems?:
    | {
        parentLink: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: string | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: string | Post;
              } | null);
          url?: string | null;
          label: string;
        };
        /**
         * Add sub‑links to create a dropdown menu.
         */
        children?:
          | {
              childLink: {
                type?: ('reference' | 'custom') | null;
                newTab?: boolean | null;
                reference?:
                  | ({
                      relationTo: 'pages';
                      value: string | Page;
                    } | null)
                  | ({
                      relationTo: 'posts';
                      value: string | Post;
                    } | null);
                url?: string | null;
                label: string;
              };
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  ctaButton: {
    ctaLink: {
      type?: ('reference' | 'custom') | null;
      newTab?: boolean | null;
      reference?:
        | ({
            relationTo: 'pages';
            value: string | Page;
          } | null)
        | ({
            relationTo: 'posts';
            value: string | Post;
          } | null);
      url?: string | null;
      label: string;
    };
  };
  /**
   * Overlay applied before the user scrolls.
   */
  headerGradient?: string | null;
  headerOverlayOpacity?: number | null;
  colors: {
    primaryColor: string;
    secondaryColor: string;
    linkColor: string;
    bodyBgColor: string;
  };
  /**
   * Used on pages that do not specify their own background image.
   */
  defaultBackgroundImage?: (string | null) | Media;
  /**
   * Overlay colour for the default background.
   */
  defaultOverlayColor?: string | null;
  /**
   * 0 = fully transparent, 1 = solid.
   */
  defaultOverlayOpacity?: number | null;
  /**
   * Used when a page does not specify its own content width.
   */
  defaultContentWidth?: ('contained' | 'full') | null;
  typography?: {
    fontPreset?: ('luxury' | 'elegant' | 'minimal' | 'caribbean' | 'baskervvillePrompt') | null;
    headingFontFamily?: string | null;
    bodyFontFamily?: string | null;
    h1FontSize?: string | null;
    h1FontWeight?: string | null;
    h2FontSize?: string | null;
    h2FontWeight?: string | null;
    h3FontSize?: string | null;
    h3FontWeight?: string | null;
    h4FontSize?: string | null;
    h4FontWeight?: string | null;
  };
  hero?: {
    headingFontFamily?: string | null;
    subheadingFontFamily?: string | null;
  };
  buttons?: {
    buttonBgColor?: string | null;
    buttonTextColor?: string | null;
    buttonHoverBgColor?: string | null;
    buttonHoverTextColor?: string | null;
    buttonBorderRadius?: string | null;
  };
  tracking?: {
    /**
     * Your GA4 measurement ID (starts with G-)
     */
    googleAnalyticsId?: string | null;
    /**
     * Container ID (starts with GTM-)
     */
    googleTagManagerId?: string | null;
    /**
     * Your Facebook/Meta Pixel ID (numeric)
     */
    metaPixelId?: string | null;
    /**
     * Paste any custom scripts to be inserted in the <head>.
     */
    customHeadScripts?: string | null;
    /**
     * Paste scripts to be placed at the end of the <body>.
     */
    customBodyScripts?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  navItems?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  layout?: T;
  navItems?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
            };
        id?: T;
      };
  logo?: T;
  description?: T;
  socialBadges?:
    | T
    | {
        image?: T;
        link?: T;
        id?: T;
      };
  reachUs?:
    | T
    | {
        heading?: T;
        phone?: T;
        email?: T;
        hours?: T;
        partnerHotel?:
          | T
          | {
              label?: T;
              logo?: T;
              link?: T;
              newTab?: T;
            };
      };
  mapEmbedUrl?: T;
  copyright?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings_select".
 */
export interface SettingsSelect<T extends boolean = true> {
  branding?:
    | T
    | {
        logo?: T;
        logoDark?: T;
        logoWidthDesktop?: T;
        logoWidthMobile?: T;
        favicon?: T;
        favicon16?: T;
        appleTouchIcon?: T;
        manifest?: T;
        androidChrome192?: T;
        androidChrome512?: T;
      };
  defaultSeo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  keywords?: T;
  phoneNumber?: T;
  navItems?:
    | T
    | {
        parentLink?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
            };
        children?:
          | T
          | {
              childLink?:
                | T
                | {
                    type?: T;
                    newTab?: T;
                    reference?: T;
                    url?: T;
                    label?: T;
                  };
              id?: T;
            };
        id?: T;
      };
  ctaButton?:
    | T
    | {
        ctaLink?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
            };
      };
  headerGradient?: T;
  headerOverlayOpacity?: T;
  colors?:
    | T
    | {
        primaryColor?: T;
        secondaryColor?: T;
        linkColor?: T;
        bodyBgColor?: T;
      };
  defaultBackgroundImage?: T;
  defaultOverlayColor?: T;
  defaultOverlayOpacity?: T;
  defaultContentWidth?: T;
  typography?:
    | T
    | {
        fontPreset?: T;
        headingFontFamily?: T;
        bodyFontFamily?: T;
        h1FontSize?: T;
        h1FontWeight?: T;
        h2FontSize?: T;
        h2FontWeight?: T;
        h3FontSize?: T;
        h3FontWeight?: T;
        h4FontSize?: T;
        h4FontWeight?: T;
      };
  hero?:
    | T
    | {
        headingFontFamily?: T;
        subheadingFontFamily?: T;
      };
  buttons?:
    | T
    | {
        buttonBgColor?: T;
        buttonTextColor?: T;
        buttonHoverBgColor?: T;
        buttonHoverTextColor?: T;
        buttonBorderRadius?: T;
      };
  tracking?:
    | T
    | {
        googleAnalyticsId?: T;
        googleTagManagerId?: T;
        metaPixelId?: T;
        customHeadScripts?: T;
        customBodyScripts?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSchedulePublish".
 */
export interface TaskSchedulePublish {
  input: {
    type?: ('publish' | 'unpublish') | null;
    locale?: string | null;
    doc?:
      | ({
          relationTo: 'pages';
          value: string | Page;
        } | null)
      | ({
          relationTo: 'posts';
          value: string | Post;
        } | null);
    global?: string | null;
    user?: (string | null) | User;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BannerBlock".
 */
export interface BannerBlock {
  style: 'info' | 'warning' | 'error' | 'success';
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'banner';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CodeBlock".
 */
export interface CodeBlock {
  language?: ('typescript' | 'javascript' | 'css') | null;
  code: string;
  id?: string | null;
  blockName?: string | null;
  blockType: 'code';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}